### ISSUE TITLE
Refactor base & modules.

### ISSUE THREAD

**Issue by H3xadecimal** [HexadecimalPython/Xeili-DiscordBot#27] opened 2017-09-17 09:49 UTC
With the new database system in place, room was cleared for improvement, and being unhappy about the base of the bot, I've decided to refactor it, and move everything* that was in the json file to the database itself.

Optimization and completion of leftover code will be done

Modules* in Development is gonna be complete and ready to use /w more explanation later on.

Overall usability, reliability and management will be improved after this update.

**Comment by HexadecimalPython** [comment] 2017-09-28 15:57
Update:
DataIO refactored in: de64d9d
Eval refactored in: 20c04cd

**Comment by HexadecimalPython** [comment] 2017-09-29 16:13
`set avatar` seems to be broken, outputting the error code, likely caused by improper argument phasing.

**Comment by HexadecimalPython** [comment] 2017-10-05 10:59
Update:
`set avatar` fixed in: b543d83 by @Ovyerus

**Comment by Ovyerus** [comment] 2017-12-17 08:54
Update:
(Finally) moved `send_cmd_help` function into dusk: 5a806a8

**Closed as completed** 2018-01-27 14:16 UTC
Labels: enhancement
